version: '3.9'

services:
  postgres:
    image: postgres:17.5-bookworm
    container_name: postgres_c
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres_network

  app:
    build: .
    container_name: postgres_app
    depends_on:
      - postgres
    networks:
      - postgres_network

volumes:
  pgdata:

networks:
  postgres_network: